name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Sitemap with Valid Lastmod Format
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          base_url="https://www.lv33global.com"

          find . -type f -name "*.html" | grep -vE '404|error|offline' | while read file; do
            path=${file#./}
            dir=$(dirname "$path")

            # Proper lastmod date format
            lastmod=$(git log -1 --format="%cd" --date=format:"%Y-%m-%d" "$file")
            if [[ -z "$lastmod" ]]; then lastmod=$(date "+%Y-%m-%d"); fi

            # Format SEO-friendly URLs
            if [[ "$path" == */index.html ]]; then
              url="${base_url}/${dir}/"
              priority=1.0
            elif [[ "$path" == "index.html" ]]; then
              url="${base_url}/"
              priority=1.0
            else
              url="${base_url}/${path}"
              priority=0.8
            fi

            url="${url%/}/"

            if [[ "$path" == *"contact"* || "$path" == *"about"* ]]; then
              priority=0.5
            fi

            echo "  <url>" >> sitemap.xml
            echo "    <loc>${url}</loc>" >> sitemap.xml
            echo "    <lastmod>${lastmod}</lastmod>" >> sitemap.xml
            echo "    <priority>${priority}</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

          # 🔥 FINAL CLEANUP: remove unexpected script garbage
          sed -i '/<script/d' sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m '✅ FINAL sitemap cleaned and ready for indexing [skip ci]' || echo "No changes"
          git push

      - name: Ping Bing Only (Google ping deprecated)
        run: |
          curl https://www.bing.com/ping?sitemap=https://www.lv33global.com/sitemap.xml
